teams_2021 = ['Premier League', 'Manchester City', 'Liverpool', 'Chelsea', 'West Ham', 'Manchester Utd',
              'Arsenal',
              'Wolves',
              'Tottenham', 'Brighton', 'Southampton', 'Leicester City', 'Aston Villa', 'Crystal Palace', 'Brentford',
              'Leeds United',
              'Everton',
              'Newcastle Utd', 'Norwich City', 'Watford', 'Burnley', 'La Liga', 'Rayo Vallecano', 'RC Celta Vigo',
              'Granada', 'Athletic Bilbao', 'Cadiz',
              'Osasuna', 'Barcelona', 'Elche', 'Real Madrid', 'Getafe', 'Deportivo', 'Real Betis', 'Mallorca',
              'Real Sociedad', 'Villarreal',
              'Espanyol', 'Valencia', 'Levante', 'Atletico', 'Sevilla', 'Bundesliga', 'Bayern München',
              'FC Schalke 04',
              'Eintracht Frankfurt', 'Arminia Bielefeld', '1. FC Union Berlin', 'FC Augsburg', '1. FC Köln',
              'TSG 1899 Hoffenheim', 'Werder Bremen', 'Hertha BSC', 'VfB Stuttgart', 'SC Freiburg', 'Borussia Dortmund',
              'Bor. Mönchengladbach', 'RB Leipzig', '1. FSV Mainz 05', 'VfL Wolfsburg', 'Bayer 04 Leverkusen']

teams_2020 = ['Premier League', 'Manchester City', 'Manchester Utd', 'Liverpool', 'Chelsea', 'Leicester City',
              'West Ham', 'Tottenham', 'Arsenal', 'Leeds United', 'Everton', 'Aston Villa', 'Newcastle Utd',
              'Wolves', 'Crystal Palace', 'Southampton', 'Brighton', 'Burnley', 'Fulham', 'West Brom', 'Sheffield Utd',
              'La Liga', 'Rayo Vallecano', 'RC Celta Vigo', 'Granada',
              'Athletic Bilbao',
              'Cadiz',
              'Osasuna', 'Barcelona', 'Elche', 'Real Madrid', 'Getafe', 'Deportivo', 'Real Betis', 'Mallorca',
              'Real Sociedad',
              'Villarreal', 'Espanyol', 'Valencia', 'Levante', 'Atletico', 'Sevilla', 'Bundesliga', 'Bayern München',
              'FC Schalke 04',
              'Eintracht Frankfurt', 'Arminia Bielefeld', '1. FC Union Berlin', 'FC Augsburg', '1. FC Köln',
              'TSG 1899 Hoffenheim', 'Werder Bremen', 'Hertha BSC', 'VfB Stuttgart', 'SC Freiburg', 'Borussia Dortmund',
              'Bor. Mönchengladbach', 'RB Leipzig', '1. FSV Mainz 05', 'VfL Wolfsburg', 'Bayer 04 Leverkusen']

teams_2019 = ['Premier League', 'Liverpool', 'Manchester City', 'Manchester Utd', 'Chelsea', 'Leicester City',
              'Tottenham', 'Wolves', 'Arsenal', 'Sheffield Utd', 'Burnley', 'Southampton', 'Everton', 'Newcastle Utd',
              'Crystal Palace', 'Brighton', 'West Ham', 'Aston Villa', 'Bournemouth', 'Watford', 'Norwich City',
              'La Liga', 'Rayo Vallecano', 'RC Celta Vigo', 'Granada',
              'Athletic Bilbao',
              'Cadiz',
              'Osasuna', 'Barcelona', 'Elche', 'Real Madrid', 'Getafe', 'Deportivo', 'Real Betis', 'Mallorca',
              'Real Sociedad',
              'Villarreal', 'Espanyol', 'Valencia', 'Levante', 'Atletico', 'Sevilla', 'Bundesliga', 'Bayern München',
              'FC Schalke 04',
              'Eintracht Frankfurt', 'Arminia Bielefeld', '1. FC Union Berlin', 'FC Augsburg', '1. FC Köln',
              'TSG 1899 Hoffenheim', 'Werder Bremen', 'Hertha BSC', 'VfB Stuttgart', 'SC Freiburg', 'Borussia Dortmund',
              'Bor. Mönchengladbach', 'RB Leipzig', '1. FSV Mainz 05', 'VfL Wolfsburg', 'Bayer 04 Leverkusen']

teams_2018 = ['Premier League', 'Manchester City', 'Liverpool', 'Chelsea', 'Tottenham', 'Arsenal', 'Manchester Utd',
              'Wolves', 'Everton', 'Leicester City', 'West Ham', 'Watford', 'Crystal Palace', 'Newcastle Utd',
              'Bournemouth', 'Burnley', 'Southampton', 'Brighton', 'Cardiff City', 'Fulham', 'Huddersfield',
              'La Liga', 'Rayo Vallecano', 'RC Celta Vigo', 'Granada',
              'Athletic Bilbao',
              'Cadiz',
              'Osasuna', 'Barcelona', 'Elche', 'Real Madrid', 'Getafe', 'Deportivo', 'Real Betis', 'Mallorca',
              'Real Sociedad',
              'Villarreal', 'Espanyol', 'Valencia', 'Levante', 'Atletico', 'Sevilla', 'Bundesliga', 'Bayern München',
              'FC Schalke 04',
              'Eintracht Frankfurt', 'Arminia Bielefeld', '1. FC Union Berlin', 'FC Augsburg', '1. FC Köln',
              'TSG 1899 Hoffenheim', 'Werder Bremen', 'Hertha BSC', 'VfB Stuttgart', 'SC Freiburg', 'Borussia Dortmund',
              'Bor. Mönchengladbach', 'RB Leipzig', '1. FSV Mainz 05', 'VfL Wolfsburg', 'Bayer 04 Leverkusen']

teams_2017 = ['Premier League', 'Manchester City', 'Manchester Utd', 'Tottenham', 'Liverpool', 'Chelsea', 'Arsenal',
              'Burnley', 'Everton', 'Leicester City', 'Newcastle Utd', 'Crystal Palace', 'Bournemouth', 'West Ham',
              'Watford', 'Brighton', 'Huddersfield', 'Southampton', 'Swansea City', 'Stoke City', 'West Brom',
              'La Liga', 'Rayo Vallecano', 'RC Celta Vigo', 'Granada',
              'Athletic Bilbao',
              'Cadiz',
              'Osasuna', 'Barcelona', 'Elche', 'Real Madrid', 'Getafe', 'Deportivo', 'Real Betis', 'Mallorca',
              'Real Sociedad',
              'Villarreal', 'Espanyol', 'Valencia', 'Levante', 'Atletico', 'Sevilla', 'Bundesliga', 'Bayern München',
              'FC Schalke 04',
              'Eintracht Frankfurt', 'Arminia Bielefeld', '1. FC Union Berlin', 'FC Augsburg', '1. FC Köln',
              'TSG 1899 Hoffenheim', 'Werder Bremen', 'Hertha BSC', 'VfB Stuttgart', 'SC Freiburg', 'Borussia Dortmund',
              'Bor. Mönchengladbach', 'RB Leipzig', '1. FSV Mainz 05', 'VfL Wolfsburg', 'Bayer 04 Leverkusen']
